"""Generate odcs.css — the same tokens as CSS custom properties for web tools.

    python -m odcs_ui.web > odcs.css

Light is the default; dark applies with the OS preference or an explicit
<html data-theme="dark">. The accent follows the OS through the CSS system
colors AccentColor / AccentColorText where the browser supports them, with
the token value as fallback.
"""
from __future__ import annotations

import sys

from . import color, tokens

HEADER = "/* ODCS App Studio tokens — generated by `python -m odcs_ui.web`. Do not edit by hand. */\n"


def _var(name: str) -> str:
    return "--odcs-" + name.lower().replace("_", "-")


def _block(selector: str, values: dict[str, str]) -> str:
    lines = [f"  {_var(k)}: {v};" for k, v in sorted(values.items())]
    return f"{selector} {{\n" + "\n".join(lines) + "\n}\n"


def css() -> str:
    light, dark = tokens.LIGHT, tokens.DARK
    scale = tokens.SCALE
    scale_vars = {f"SPACE_{i + 1}": f"{v}px" for i, v in enumerate(scale["space"])}
    scale_vars.update({"RADIUS_CONTROL": f"{scale['radius']['control']}px",
                       "RADIUS_CARD": f"{scale['radius']['card']}px",
                       "RADIUS_PILL": f"{scale['radius']['pill']}px",
                       "CONTROL_HEIGHT": f"{scale['controlHeight']}px",
                       "FOCUS_WIDTH": f"{scale['focusWidth']}px"})
    out = [HEADER]
    out.append(_block(":root", {**light, **scale_vars, "COLOR_SCHEME": "light"}).replace(
        "--odcs-color-scheme: light;", "color-scheme: light;"))
    dark_block = _block(":root", {**dark, "COLOR_SCHEME": "dark"}).replace(
        "--odcs-color-scheme: dark;", "color-scheme: dark;")
    out.append("@media (prefers-color-scheme: dark) {\n" +
               "\n".join("  " + line for line in dark_block.replace(":root", ':root:not([data-theme="light"])').splitlines()) + "\n}\n")
    out.append(dark_block.replace(":root", ':root[data-theme="dark"]'))
    out.append(":root[data-theme=\"light\"] { color-scheme: light; }\n")
    out.append("@supports (color: AccentColor) {\n  :root { --odcs-accent: AccentColor; --odcs-text-on-accent: AccentColorText; }\n}\n")
    # Documented pairing so the fallback accent keeps its contrast guarantee.
    out.append(f"/* fallback accents: light {light['ACCENT']} on-accent {color.on_accent(light['ACCENT'])}; "
               f"dark {dark['ACCENT']} on-accent {color.on_accent(dark['ACCENT'])} */\n")
    return "\n".join(out)


if __name__ == "__main__":
    sys.stdout.write(css())
